### ISSUE TITLE
SOPS implementation is insecure for a multi-user setup

### ISSUE THREAD

**Issue by nicolas-goudry** [nicolas-goudry/nix-config#2]
## Context

Secrets management is implemented using SOPS [^1]. Integration to NixOS (and Home Manager) is taken care of by sops-nix [^2].

Secrets are configured in a SOPS config file [^3] at the root of the repository. This configuration file looks something like the following:

```yaml
keys:
  users:
    - &usera <pgp-key-id>
  hosts:
    - &hosta <public-age-key>
    - &hostb <public-age-key>
creation_rules:
  - path_regex: secrets.ya?ml$
    key_groups:
      - pgp:
          - *usera
        age:
          - *hosta
          - *hostb
```

## Current behavior

Everything is working fine in a single user setup, however I fear that having a single key group which handles each and every secret in the repository would make a multi-user setup insecure.

Indeed, having a single key group means that each and every authorized host and trusted user is able to view all secrets. `usera` would therefore be able to view the secrets of `userb`, which is not really acceptable.

## Expected behavior

In a perfect setup, one would want the following:

- secrets of `usera` cannot be decrypted by `userb` (and vice-versa)
- some secrets can be decrypted by `usera` and `userb` but do not require both user keys

> [!NOTE]
> Authorized hosts should always be able to decrypt secrets on their own, else sops-nix activation would fail.

[^1]: https://getsops.io/
[^2]: https://github.com/Mic92/sops-nix
[^3]: https://github.com/nicolas-goudry/nix-config/blob/main/.sops.yaml

**Comment by nicolas-goudry** [comment]
After some tests with the `sops` tool, I found out the following:

* using standalone keys for a given creation rule will require all keys to encrypt but only one to decrypt

```yaml
creation_rule:
- path_regex: test.yaml
  age: age12345…
  pgp: F2DC3BA8…
```

* using a key group with keys of multiple formats will require all keys to encrypt but only one to decrypt

```yaml
creation_rule:
- path_regex: test.yaml
  key_groups:
  - age:
    - age12345…
    pgp:
    - F2DC3BA8…
```

* using multiple key groups will require all keys to encrypt and at least one key of each group to decrypt

```yaml
creation_rule:
- path_regex: test.yaml
  key_groups:
  - age:
    - age12345…
  - pgp:
    - F2DC3BA8…
```
